#!/bin/bash


echo "-------------------------------"
echo "Execution program initialized"
echo "Installing Trackermon"
echo "-------------------------------"

echo ""

sudo rm -f /var/log/trackermon.log

sudo touch /var/log/trackermon.log
sudo chown -R $USER:$USER /var/log/trackermon.log
chmod +rwx /var/log/trackermon.log

echo "Creating trackermon.log file"

sudo mkdir /etc/trackermon
echo "Creating directory at /etc/trackermon"

sudo cp config.conf /etc/trackermon

echo "Compiling Trackermon Code"
gcc trackermon.c -o trackermon

sudo cp trackermon /usr/sbin/

echo "Setup complete"

echo "Initizialing Service"

sudo cp trackermon.service /etc/systemd/system/

sudo systemctl enable trackermon.service

sudo systemctl daemon-reload

sudo systemctl start trackermon.service

echo "Creating and starting trackermon systemd service...done"
echo ""
echo "Installation finalized"
