#!/bin/bash


echo "-------------------------------"
echo "Execution program initialized"
echo "Installing Trackermon"
echo "-------------------------------"

echo ""

sudo touch /var/log/trackermon.log
sudo chown -R $USER:$USER /var/log/trackermon.log
chmod +rwx /var/log/file

echo "Creating log file"

sudo mkdir /etc/trackermon
echo "Creating directory at /etc/trackermon"

sudo cp config.conf /etc/trackermon

echo "Compiling Code"
gcc trackermon.c -o trackermon

sudo cp trackermon /etc/trackermon

//sudo cp h_trackermon.sh /etc/trackermon

echo "Setup complete"

echo "Initizialing Service"

sudo cp trackermon.service /etc/systemd/system

sudo systemctl daemon-reload

sudo systemctl enable trackermon.service

sudo systemctl start trackermon.service

echo "Creating trackermon systemd service...done"
echo ""
echo "Installation finalized"
