#!/bin/sh
#
#       /etc/init.d/trackermon
# 
# chkconfig --add trackermon
# chkconfig: 5 20 80
# chkconfig --level 5 trackermon on 
# chkconfig --list | grep trackermon
# description: Example of UNIX daemon


### BEGIN INIT INFO
# Provides:       trackermon
# Required-Start: $rsyslog
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start: 5
# Default-Stop:  0 1 6
# Short-Description: start and stop example of daemon
# Description: Example of UNIX daemon
### END INIT INFO

. /etc/init.d/trackermon

prog = "trackermon"
app = "/usr/bin/$prog"
log_file = "/var/log/$prog.log"
conf_file = "/etc/trackermon/config.conf"
prog_user = root

start() {
    
}

stop() {
    # code to stop app comes here 
    # example: killproc program_name
}

case "$1" in 
    start)
       start
       ;;
    stop)
       stop
       ;;
    restart)
       stop
       start
       ;;
    status)
       # code to check status of app comes here 
       # example: status program_name
       ;;
    *)
       echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0 